// internal/review/review.go
package review

import (
	"context"
	"fmt"
	"strings"
)

// Reviewer generates a structured code review from a PR context.
type Reviewer interface {
	Review(ctx context.Context, pr PRContext) (*ReviewResult, error)
}

type RepoInstructions struct {
	RepoWide          string   // from .github/copilot-instructions.md
	PathSpecific      []string // from matching .github/instructions/*.instructions.md
	AgentInstructions string   // from AGENTS.md
}

type PRContext struct {
	Owner            string
	Repo             string
	Number           int
	Title            string
	Description      string
	Diff             string
	Files            []string
	Instructions     string
	Model            string
	RepoInstructions RepoInstructions
	HeadSHA          string
}

// ReviewUsage holds token and premium request counts from the AI provider.
type ReviewUsage struct {
	InputTokens     int
	OutputTokens    int
	CacheReadTokens int
	PremiumRequests int
}

type ReviewResult struct {
	Summary  string          `json:"summary"`
	Verdict  string          `json:"verdict"`
	Comments []InlineComment `json:"comments"`
	Usage    ReviewUsage     `json:"-"` // not from AI response, populated by reviewer
}

type InlineComment struct {
	Path       string `json:"path"`
	Line       int    `json:"line"`
	Body       string `json:"body"`
	Severity   string `json:"severity"`
	Suggestion string `json:"suggestion,omitempty"`
}

// FormattedBody returns the comment body formatted for GitHub,
// with AI attribution tag, severity tag, and optional suggestion block.
func (c InlineComment) FormattedBody() string {
	var b strings.Builder

	fmt.Fprintf(&b, "> 🤖 _AI-generated_\n\n")
	fmt.Fprintf(&b, "**[%s]** %s", c.Severity, c.Body)

	if c.Suggestion != "" {
		fmt.Fprintf(&b, "\n\n```suggestion\n%s\n```", c.Suggestion)
	}

	return b.String()
}

// AIReviewFooter returns the attribution footer appended to review bodies.
func AIReviewFooter(model string) string {
	return fmt.Sprintf("\n\n---\n🤖 _This review was generated by [Proof](https://github.com/chaz8081/proof) using AI (model: %s). Comments may have been curated by the reviewer before submission._", model)
}
