// internal/cli/setup.go
package cli

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/chaz8081/proof/internal/config"
	"github.com/spf13/cobra"
)

var setupCmd = &cobra.Command{
	Use:     "setup",
	Short:   "Guided first-run configuration wizard",
	Long:    "Interactive wizard that creates ~/.proof/config.yaml with your preferences.",
	Example: "  proof setup",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfgPath := filepath.Join(config.ConfigDir(), "config.yaml")

		// Check if config already exists
		if _, err := os.Stat(cfgPath); err == nil {
			fmt.Print("Config already exists at " + cfgPath + ". Overwrite? (y/N): ")
			if !promptYesNo(os.Stdin, false) {
				cmd.Println("Setup cancelled.")
				return nil
			}
		}

		cmd.Println("Welcome to Proof! Let's get you configured.")
		cmd.Println()

		// Detect GitHub user
		username := detectGitHubUser()
		if username != "" {
			cmd.Printf("Detected GitHub user: %s\n\n", username)
		}

		reader := bufio.NewReader(os.Stdin)

		// Repos
		cmd.Print("? Repos to watch (comma-separated, e.g., owner/repo, org/*):\n> ")
		reposInput, _ := reader.ReadString('\n')
		repos := parseCSV(reposInput)
		if len(repos) == 0 {
			if username != "" {
				repos = []string{username + "/*"}
			} else {
				repos = []string{"owner/repo"}
			}
		}

		// Dual account
		var copilotToken string
		cmd.Print("\n? Do you use a separate GitHub account for Copilot AI? (y/N): ")
		if promptYesNo(os.Stdin, false) {
			cmd.Print("? Copilot token or env var (leave empty to use PROOF_COPILOT_TOKEN): ")
			copilotToken, _ = reader.ReadString('\n')
			copilotToken = strings.TrimSpace(copilotToken)
		}

		// Verdict
		cmd.Print("\n? Default review verdict (COMMENT/APPROVE/REQUEST_CHANGES) [COMMENT]: ")
		verdictInput, _ := reader.ReadString('\n')
		verdict := strings.TrimSpace(strings.ToUpper(verdictInput))
		if verdict == "" {
			verdict = "COMMENT"
		}

		// Model
		cmd.Print("\n? AI model [gpt-4.1]: ")
		modelInput, _ := reader.ReadString('\n')
		model := strings.TrimSpace(modelInput)
		if model == "" {
			model = "gpt-4.1"
		}

		// Include own
		cmd.Print("\n? Include your own PRs in batch scans? (y/N): ")
		includeOwn := promptYesNo(os.Stdin, false)

		// Generate config
		cfgContent := generateSetupConfig(repos, copilotToken, verdict, model, includeOwn)

		if err := os.MkdirAll(filepath.Dir(cfgPath), 0755); err != nil {
			return fmt.Errorf("creating config directory: %w", err)
		}
		if err := os.WriteFile(cfgPath, []byte(cfgContent), 0644); err != nil {
			return fmt.Errorf("writing config: %w", err)
		}

		cmd.Printf("\n✓ Config saved to %s\n\n", cfgPath)
		cmd.Println("Next steps:")
		cmd.Println("  1. proof poll --dry-run     # test your config")
		cmd.Println("  2. proof poll               # start reviewing")
		cmd.Println("  3. proof config show        # view your config")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(setupCmd)
}

func promptYesNo(r io.Reader, defaultVal bool) bool {
	scanner := bufio.NewScanner(r)
	if !scanner.Scan() {
		return defaultVal
	}
	input := strings.TrimSpace(strings.ToLower(scanner.Text()))
	if input == "" {
		return defaultVal
	}
	return input == "y" || input == "yes"
}

func parseCSV(input string) []string {
	var result []string
	for _, item := range strings.Split(input, ",") {
		item = strings.TrimSpace(item)
		if item != "" {
			result = append(result, item)
		}
	}
	return result
}

func generateSetupConfig(repos []string, copilotToken, verdict, model string, includeOwn bool) string {
	var b strings.Builder

	b.WriteString("# Proof configuration\n# Generated by proof setup\n\n")

	b.WriteString("repos:\n")
	for _, r := range repos {
		fmt.Fprintf(&b, "  - %s\n", r)
	}

	b.WriteString("\npoll:\n")
	b.WriteString("  ignore_drafts: true\n")
	b.WriteString("  ignore_wip: true\n")
	if includeOwn {
		b.WriteString("  include_own: true\n")
	}

	b.WriteString("\nreview:\n")
	fmt.Fprintf(&b, "  default_verdict: %s\n", verdict)
	fmt.Fprintf(&b, "  model: %s\n", model)

	if copilotToken != "" {
		b.WriteString("\nauth:\n")
		fmt.Fprintf(&b, "  copilot_token: %s\n", copilotToken)
	}

	return b.String()
}
