// internal/cli/setup.go
package cli

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/chaz8081/proof/internal/config"
	"github.com/chaz8081/proof/internal/review"
	"github.com/spf13/cobra"
)

var setupCmd = &cobra.Command{
	Use:     "setup",
	Short:   "Guided first-run configuration wizard",
	Long:    "Interactive wizard that creates ~/.proof/config.yaml with your preferences.",
	Example: "  proof setup",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfgPath := filepath.Join(config.ConfigDir(), "config.yaml")

		// Check if config already exists
		if _, err := os.Stat(cfgPath); err == nil {
			fmt.Print("Config already exists at " + cfgPath + ". Overwrite? (y/N): ")
			if !promptYesNo(os.Stdin, false) {
				cmd.Println("Setup cancelled.")
				return nil
			}
		}

		cmd.Println("Welcome to Proof! Let's get you configured.")
		cmd.Println()

		// Detect GitHub user
		username := detectGitHubUser()
		if username != "" {
			cmd.Printf("Detected GitHub user: %s\n\n", username)
		}

		reader := bufio.NewReader(os.Stdin)

		// Repos
		cmd.Print("? Repos to watch (comma-separated, e.g., owner/repo, org/*):\n> ")
		reposInput, _ := reader.ReadString('\n')
		repos := parseCSV(reposInput)
		if len(repos) == 0 {
			if username != "" {
				repos = []string{username + "/*"}
			} else {
				repos = []string{"owner/repo"}
			}
		}

		// Detect gh accounts
		accounts, _ := listGHAccounts()

		var copilotAccount, reviewerAccount string

		if len(accounts) > 1 {
			cmd.Println()
			cmd.Println("GitHub accounts detected:")
			for i, a := range accounts {
				cmd.Printf("  %d. %s\n", i+1, a)
			}

			cmd.Printf("\n? Which account has Copilot? [1]: ")
			copilotInput, _ := reader.ReadString('\n')
			copilotIdx := parseIndex(copilotInput, len(accounts))
			copilotAccount = accounts[copilotIdx]

			cmd.Printf("? Which account should post reviews? [1]: ")
			reviewerInput, _ := reader.ReadString('\n')
			reviewerIdx := parseIndex(reviewerInput, len(accounts))
			reviewerAccount = accounts[reviewerIdx]

			if copilotAccount == reviewerAccount {
				copilotAccount = "" // same account, no need to store
				reviewerAccount = ""
			}
		} else if len(accounts) == 1 {
			cmd.Printf("\nGitHub account: %s\n", accounts[0])
		}

		// Verdict
		cmd.Print("\n? Default review verdict (COMMENT/APPROVE/REQUEST_CHANGES) [COMMENT]: ")
		verdictInput, _ := reader.ReadString('\n')
		verdict := strings.TrimSpace(strings.ToUpper(verdictInput))
		if verdict == "" {
			verdict = "COMMENT"
		}

		// Model selection
		model := "gpt-4.1" // default
		copilotToken := ""
		if copilotAccount != "" {
			t, _ := ghAuthToken(copilotAccount)
			copilotToken = t
		} else if len(accounts) > 0 {
			t, _ := ghAuthToken(accounts[0])
			copilotToken = t
		}

		models, err := review.ListModels(cmd.Context(), copilotToken)
		if err == nil && len(models) > 0 {
			cmd.Println("\nAvailable AI models:")
			for i, m := range models {
				name := m.Name
				if name == "" {
					name = m.ID
				}
				cmd.Printf("  %d. %s\n", i+1, name)
			}
			cmd.Printf("\n? Select a model [1]: ")
			modelInput, _ := reader.ReadString('\n')
			modelIdx := parseIndex(modelInput, len(models))
			model = models[modelIdx].ID
		} else {
			cmd.Print("\n? AI model [gpt-4.1]: ")
			modelInput, _ := reader.ReadString('\n')
			if m := strings.TrimSpace(modelInput); m != "" {
				model = m
			}
		}

		// Include own
		cmd.Print("\n? Include your own PRs in batch scans? (y/N): ")
		includeOwn := promptYesNo(os.Stdin, false)

		// Generate config
		cfgContent := generateSetupConfig(repos, copilotAccount, reviewerAccount, verdict, model, includeOwn)

		if err := os.MkdirAll(filepath.Dir(cfgPath), 0700); err != nil {
			return fmt.Errorf("creating config directory: %w", err)
		}
		if err := os.WriteFile(cfgPath, []byte(cfgContent), 0600); err != nil {
			return fmt.Errorf("writing config: %w", err)
		}

		cmd.Printf("\n✓ Config saved to %s\n\n", cfgPath)
		cmd.Println("Next steps:")
		cmd.Println("  1. proof poll --dry-run     # test your config")
		cmd.Println("  2. proof poll               # start reviewing")
		cmd.Println("  3. proof config show        # view your config")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(setupCmd)
}

func promptYesNo(r io.Reader, defaultVal bool) bool {
	scanner := bufio.NewScanner(r)
	if !scanner.Scan() {
		return defaultVal
	}
	input := strings.TrimSpace(strings.ToLower(scanner.Text()))
	if input == "" {
		return defaultVal
	}
	return input == "y" || input == "yes"
}

func parseCSV(input string) []string {
	var result []string
	for _, item := range strings.Split(input, ",") {
		item = strings.TrimSpace(item)
		if item != "" {
			result = append(result, item)
		}
	}
	return result
}

func generateSetupConfig(repos []string, copilotAccount, reviewerAccount, verdict, model string, includeOwn bool) string {
	var b strings.Builder

	b.WriteString("# Proof configuration\n# Generated by proof setup\n\n")

	b.WriteString("repos:\n")
	for _, r := range repos {
		fmt.Fprintf(&b, "  - %s\n", r)
	}

	b.WriteString("\npoll:\n")
	b.WriteString("  ignore_drafts: true\n")
	b.WriteString("  ignore_wip: true\n")
	if includeOwn {
		b.WriteString("  include_own: true\n")
	}

	b.WriteString("\nreview:\n")
	fmt.Fprintf(&b, "  default_verdict: %s\n", verdict)
	fmt.Fprintf(&b, "  model: %s\n", model)

	if copilotAccount != "" || reviewerAccount != "" {
		b.WriteString("\nauth:\n")
		if reviewerAccount != "" {
			fmt.Fprintf(&b, "  reviewer: %s\n", reviewerAccount)
		}
		if copilotAccount != "" {
			fmt.Fprintf(&b, "  copilot: %s\n", copilotAccount)
		}
	}

	return b.String()
}

func parseIndex(input string, max int) int {
	input = strings.TrimSpace(input)
	if input == "" {
		return 0
	}
	n, err := strconv.Atoi(input)
	if err != nil || n < 1 || n > max {
		return 0
	}
	return n - 1
}
